apiVersion: v1
kind: Service
metadata:
  name: counter-np # Service 이름
spec:
  type: NodePort # Service 타입 (NodePort: 외부에서 노드 IP:NodePort로 접근 가능)
  ports:
    - port: 3000 # Service가 노출하는 포트 (클러스터 내부에서 접근 시 사용)
      protocol: TCP # 통신 프로토콜
      nodePort: 31000 # 외부에서 접근할 노드 포트 (범위: 30000-32767)
  selector: # 트래픽을 전달할 Pod 선택 조건 (label 매칭)
    app: counter
    tier: app
