apiVersion: v1
kind: Service
metadata:
  name: counter-lb # Service 이름
spec:
  type: LoadBalancer # Service 타입 (외부 로드밸런서를 통해 외부에 노출)
  ports:
    - port: 30000 # LoadBalancer가 외부에 노출하는 포트
      targetPort: 3000 # Pod 내부 컨테이너의 포트
      protocol: TCP # 통신 프로토콜
  selector: # 트래픽을 전달할 Pod를 선택하는 라벨
    app: counter
    tier: app
