apiVersion: v1            # 사용할 Kubernetes API 버전
kind: Pod                 # 리소스 종류 (Pod)
metadata:
  name: echo              # Pod 이름
  labels:
    app: echo             # Pod에 부여할 라벨 (Service/Selector에서 사용)
spec:
  containers:
    - name: app                         # 컨테이너 이름
      image: ghcr.io/subicura/echo:v1   # 사용할 컨테이너 이미지
